import { BrowserWindow, app } from "electron";
import { inject, singleton } from "tsyringe";
import { IResult } from "../../base";
import { INFRASTRUCTURE } from "../../service.tokens";
import { ILogService, IResultFactory, IWindowsService } from "../interface";

/*
 * This allows TypeScript to pick up the magic constants that"s auto-generated by Forge"s Webpack
 * plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
 * whether you"re running in development or production).
 */
declare const FIRST_TIME_WEBPACK_ENTRY: string;
declare const FIRST_TIME_PRELOAD_WEBPACK_ENTRY: string;
declare const DECK_WINDOW_WEBPACK_ENTRY: string;
declare const DECK_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const SPLASH_WINDOW_WEBPACK_ENTRY: string;
declare const SPLASH_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

@singleton()
export class WindowsService implements IWindowsService {
  // #region private fields ---------------------------------------------------
  private readonly logService: ILogService;
  private readonly resultFactory: IResultFactory;
  private deckWindows: Map<number, BrowserWindow>;
  private _mainWindow!: BrowserWindow | null;
  private _splashWindow!: BrowserWindow | null;
  private _firstTimeWindow!: BrowserWindow | null;
  // #endregion

  // #region IWindowsService properties ---------------------------------------
  public get mainWindow(): BrowserWindow {
    return this._mainWindow!;
  }
  // #endregion

  // #region Constructor ------------------------------------------------------
  public constructor(
    @inject(INFRASTRUCTURE.ResultFactory) resultFactory: IResultFactory,
    @inject(INFRASTRUCTURE.LogService) logService: ILogService) {
    this.logService = logService;
    this.resultFactory = resultFactory;
    this.deckWindows = new Map<number, BrowserWindow>();
  }
  // #endregion

  // #region IWindowsService methods ------------------------------------------
  public createFirstTimeWindow(): BrowserWindow {
    this._firstTimeWindow = new BrowserWindow({
      height: 420,
      width: 800,
      webPreferences: {
        preload: FIRST_TIME_PRELOAD_WEBPACK_ENTRY
      },
      icon: "assets/icons/logo.ico",
      show: false,
      alwaysOnTop: true,
      frame: true,
      title: "Arcane Archive - First time use",
      useContentSize: true
    });
    this._firstTimeWindow.on("closed", () => this._firstTimeWindow = null);
    this._firstTimeWindow.removeMenu();
    this._firstTimeWindow.loadURL(FIRST_TIME_WEBPACK_ENTRY);
    if (!app.isPackaged) {
      this._firstTimeWindow.webContents.openDevTools({ mode: "undocked" });
    }

    return this._firstTimeWindow;
  }

  public createMainWindow(): BrowserWindow {
    this._mainWindow = new BrowserWindow({
      height: 600,
      width: 800,
      icon: "assets/icons/logo.ico",
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
      },
      show: false,
      title: "Arcane Archive"
    });
    this._mainWindow.on("closed", () => this._mainWindow = null);
    this._mainWindow.removeMenu();
    void this._mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    if (!app.isPackaged) {
      this._mainWindow.webContents.openDevTools({ mode: "undocked" });
    }

    return this._mainWindow;
  }

  public createSplashWindow(): BrowserWindow {
    this._splashWindow = new BrowserWindow({
      height: 506,
      width: 900,
      webPreferences: {
        preload: SPLASH_WINDOW_PRELOAD_WEBPACK_ENTRY
      },
      show: false,
      alwaysOnTop: true,
      frame: false,
      resizable: false
    });
    this._splashWindow.on("closed", () => this._splashWindow = null);
    void this._splashWindow.loadURL(SPLASH_WINDOW_WEBPACK_ENTRY);
    return this._splashWindow;
  }

  public getDeckWindow(deckId: number): void {
    let deckWindow = this.deckWindows.get(deckId);
    if (deckWindow == undefined) {
      this.logService.debug("Main", "Creating new window");
      deckWindow = new BrowserWindow({
        height: 800,
        width: 1200,
        webPreferences: {
          preload: DECK_WINDOW_PRELOAD_WEBPACK_ENTRY
        },
        show: false,
        alwaysOnTop: false,
        frame: true
      });
      deckWindow.on("closed", () => {
        const closingWindow = [...this.deckWindows].find((value: [number, BrowserWindow]) => value[1] === deckWindow);
        if (closingWindow != undefined) {
          this.logService.debug("Main", "removing deck window from map");
          this.deckWindows.delete(closingWindow[0]);
        } else {
          this.logService.debug("Main", "deck window not found");
        }
      });

      this.deckWindows.set(deckId, deckWindow);
      void deckWindow.loadURL(`${DECK_WINDOW_WEBPACK_ENTRY}?id=${deckId}`);
      deckWindow.on("ready-to-show", () => deckWindow!.show());
    } else {
      this.logService.debug("Main", "Focus existing deck window");
      deckWindow.focus();
    }
  }

  public showMainWindow(): Promise<IResult<void>> {
    if (this._mainWindow) {
      this._mainWindow.show();
    }
    if (this._splashWindow) {
      this._splashWindow.close();
    }
    return this.resultFactory.createNoContentResultPromise();
  };

  public hideSplashWindow(): Promise<IResult<void>> {
    if (this._splashWindow) {
      this._splashWindow.hide();
    }
    return this.resultFactory.createNoContentResultPromise();
  }

  public showSplashWindow(): Promise<IResult<void>> {
    if (this._splashWindow) {
      this._splashWindow.show();
    }
    return this.resultFactory.createNoContentResultPromise();
  }

  public showFirstTimeWindow(): Promise<IResult<void>> {
    if (this._firstTimeWindow) {
      this._firstTimeWindow.show();
    }
    if (this._splashWindow) {
      this._splashWindow.hide();
    }
    return this.resultFactory.createNoContentResultPromise();
  }
  // #endregion
}
